-- Add personal information columns to general_users table
ALTER TABLE general_users
ADD COLUMN IF NOT EXISTS phone VARCHAR(20) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS address VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS city VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS state VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20) DEFAULT NULL;

-- Verify the changes
DESCRIBE general_users;
